# Generated by Django 3.0.8 on 2020-08-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoClass2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(db_column='title', max_length=20),
        ),
        migrations.AlterField(
            model_name='pocketinfo',
            name='pcomment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
