# Generated by Django 3.0.8 on 2020-08-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoClassapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pocketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pgender', models.BooleanField()),
                ('pcomment', models.CharField(max_length=100)),
                ('pbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoClassapp.BookInfo')),
            ],
        ),
    ]
